const { vec } = require('./vector');

const img = (id, extra = '') =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=72${extra}`;

const products = [
  {
    id: 'mare-01',
    name: 'Vestido Medianoche de Lino',
    brand: 'MARE Atelier',
    price: 168,
    kind: 'garment',
    fabric: 'Lino lavado',
    colors: ['Negro carbón', 'Tinta'],
    sizes: ['XS', 'S', 'M', 'L'],
    image: img('photo-1496747611176-843222e1e195'),
    blurb: 'Corte fluido que se mueve con el viento salado cuando cae el sol.',
    description:
      'Midi de lino lavado, silueta sesgada y tira fina. Pensado para cenas frente al mar cuando la luz ya no es de día. Transpira, no brilla en exceso y cubre sin calor.',
    tags: ['lino', 'midi', 'anochecer', 'mar', 'fluido'],
    vector: vec({
      beach: 0.96,
      night: 0.97,
      summer: 0.82,
      casual: 0.45,
      formal: 0.38,
      outdoor: 0.84,
      light: 0.9,
      dark: 0.92,
      dress: 1,
      layering: 0.15,
      comfort: 0.72,
      luxury: 0.7,
      romantic: 0.78,
      linen: 1,
      nature: 0.55,
      travel: 0.4,
    }),
  },
  {
    id: 'mare-02',
    name: 'Caftán Crepúsculo',
    brand: 'Costa Quiet',
    price: 142,
    kind: 'look',
    fabric: 'Viscosa vaporosa',
    colors: ['Humo', 'Oro viejo'],
    sizes: ['Único'],
    image: img('photo-1515886657613-9f3515e0c046'),
    blurb: 'Una sola pieza que funciona como look completo al borde del agua.',
    description:
      'Caftán largo de viscosa que cubre el traje de baño o se usa solo. Caída editorial, manga kimono y cinturón suave para el momento en que el cielo se vuelve violeta.',
    tags: ['caftan', 'cover', 'editorial', 'mar', 'verano'],
    vector: vec({
      beach: 0.98,
      night: 0.8,
      day: 0.25,
      summer: 0.9,
      casual: 0.5,
      outdoor: 0.9,
      light: 0.88,
      dark: 0.55,
      dress: 0.7,
      swim: 0.35,
      layering: 0.7,
      luxury: 0.62,
      romantic: 0.6,
      linen: 0.2,
      nature: 0.5,
    }),
  },
  {
    id: 'mare-03',
    name: 'Camisa Negra de Lino Oversize',
    brand: 'Sal',
    price: 98,
    kind: 'garment',
    fabric: 'Lino belga',
    colors: ['Negro'],
    sizes: ['S', 'M', 'L', 'XL'],
    image: img('photo-1617127365659-c47fa864d8bc'),
    blurb: 'La capa ligera que pides cuando baja la brisa del agua.',
    description:
      'Camisa oversize de lino belga, abierta sobre la piel o abotonada. El negro evita el look de mediodía y aguanta una terraza a las diez.',
    tags: ['camisa', 'lino', 'oversize', 'capa', 'negro'],
    vector: vec({
      beach: 0.78,
      night: 0.86,
      summer: 0.75,
      casual: 0.8,
      outdoor: 0.7,
      light: 0.85,
      dark: 0.95,
      mens: 0.45,
      layering: 0.9,
      comfort: 0.88,
      linen: 1,
      travel: 0.55,
      urban: 0.4,
    }),
  },
  {
    id: 'mare-04',
    name: 'Pantalón Palazzo Arena Húmeda',
    brand: 'MARE Atelier',
    price: 128,
    kind: 'garment',
    fabric: 'Cupro fluido',
    colors: ['Arena oscura'],
    sizes: ['34', '36', '38', '40', '42'],
    image: img('photo-1509631179647-0177331693ae'),
    blurb: 'Caída ancha, cintura suave, listo para caminar del muelle al restaurante.',
    description:
      'Palazzo de cupro que no se pega al cuerpo. Tono tierra mojada: se lee de día, pero brilla bajo lámparas de exterior.',
    tags: ['palazzo', 'fluido', 'cintura', 'verano'],
    vector: vec({
      beach: 0.72,
      night: 0.7,
      summer: 0.8,
      casual: 0.6,
      outdoor: 0.65,
      light: 0.8,
      dark: 0.55,
      dress: 0.2,
      comfort: 0.84,
      luxury: 0.45,
      linen: 0.35,
      travel: 0.5,
    }),
  },
  {
    id: 'mare-05',
    name: 'Sandalias Dorado Lunar',
    brand: 'Litoral',
    price: 118,
    kind: 'footwear',
    fabric: 'Cuero metalizado',
    colors: ['Oro viejo'],
    sizes: ['36', '37', '38', '39', '40'],
    image: img('photo-1543163521-1bf539c55dd2'),
    blurb: 'Tira fina, suela baja, el brillo justo para un anochecer húmedo.',
    description:
      'Sandalia de tira fina en cuero metalizado mate. Se quita la arena de un soplo y no clava como un stiletto en madera de deck.',
    tags: ['sandalia', 'metal', 'suave', 'verano'],
    vector: vec({
      beach: 0.88,
      night: 0.9,
      summer: 0.85,
      casual: 0.35,
      formal: 0.4,
      outdoor: 0.75,
      light: 0.6,
      dark: 0.2,
      footwear: 1,
      luxury: 0.66,
      romantic: 0.72,
      metallic: 0.95,
      travel: 0.3,
    }),
  },
  {
    id: 'mare-06',
    name: 'Kimono Seda Eclipse',
    brand: 'Costa Quiet',
    price: 156,
    kind: 'garment',
    fabric: 'Seda lavada',
    colors: ['Eclipse', 'Berenjena'],
    sizes: ['S/M', 'M/L'],
    image: img('photo-1529139574466-a262682b0d2c'),
    blurb: 'Capa de seda que convierte un bañador en un look de copa.',
    description:
      'Kimono de seda lavada, peso pluma. El color eclipse absorbe la última luz y evita el blanco de toalla. Ideal sobre piel salada.',
    tags: ['kimono', 'seda', 'capa', 'noche'],
    vector: vec({
      beach: 0.9,
      night: 0.93,
      summer: 0.7,
      outdoor: 0.8,
      light: 0.86,
      dark: 0.88,
      dress: 0.4,
      swim: 0.3,
      layering: 1,
      luxury: 0.84,
      romantic: 0.7,
      metallic: 0.1,
    }),
  },
  {
    id: 'mare-07',
    name: 'Clutch Concha Bronce',
    brand: 'Sal',
    price: 86,
    kind: 'accessory',
    fabric: 'Piel metalizada',
    colors: ['Bronce'],
    sizes: ['Único'],
    image: img('photo-1591561954557-26941169b49e'),
    blurb: 'Pequeño, rígido, con eco de concha. Cabe el teléfono y el labial.',
    description:
      'Clutch rígido en forma de valva. Bronce mate que no compite con la piel bronceada y se lee joya, no souvenir.',
    tags: ['clutch', 'bronce', 'mini', 'noche'],
    vector: vec({
      beach: 0.62,
      night: 0.88,
      summer: 0.5,
      formal: 0.55,
      outdoor: 0.4,
      dark: 0.35,
      accessory: 1,
      luxury: 0.8,
      romantic: 0.65,
      metallic: 0.9,
      party: 0.45,
    }),
  },
  {
    id: 'mare-08',
    name: 'Falda Midi de Gasa Oscura',
    brand: 'MARE Atelier',
    price: 112,
    kind: 'garment',
    fabric: 'Gasa de algodón',
    colors: ['Grafito'],
    sizes: ['XS', 'S', 'M', 'L'],
    image: img('photo-1485968579580-b6d095142e6e'),
    blurb: 'Movimiento de gasa, opacidad suficiente cuando se encienden las luces.',
    description:
      'Midi de doble capa. De día parece sombra; de noche, se vuelve vestido si la subes con un top de satén.',
    tags: ['falda', 'gasa', 'midi', 'grafito'],
    vector: vec({
      beach: 0.68,
      night: 0.8,
      summer: 0.7,
      outdoor: 0.6,
      light: 0.75,
      dark: 0.9,
      dress: 0.55,
      romantic: 0.6,
      luxury: 0.5,
    }),
  },
  {
    id: 'mare-09',
    name: 'Top Cruzado de Satén',
    brand: 'Costa Quiet',
    price: 74,
    kind: 'garment',
    fabric: 'Satén de acetato',
    colors: ['Hueso oscuro', 'Negro'],
    sizes: ['XS', 'S', 'M'],
    image: img('photo-1469334031218-e382a71b716b'),
    blurb: 'Un destello controlado. No lentejuela: luz sobre agua.',
    description:
      'Top cruzado de satén mate. Refleja faroles y luna, no flashes de mediodía. Se ata y se olvida.',
    tags: ['top', 'saten', 'cruzado', 'brillo suave'],
    vector: vec({
      beach: 0.55,
      night: 0.86,
      summer: 0.6,
      party: 0.4,
      outdoor: 0.5,
      light: 0.5,
      dark: 0.6,
      dress: 0.35,
      romantic: 0.8,
      luxury: 0.58,
      metallic: 0.35,
    }),
  },
  {
    id: 'mare-10',
    name: 'Pendientes Marea',
    brand: 'Litoral',
    price: 54,
    kind: 'accessory',
    fabric: 'Plata envejecida',
    colors: ['Plata oscura'],
    sizes: ['Único'],
    image: img('photo-1535632066927-ab7c9ab60908'),
    blurb: 'Aros irregulares, como espuma quieta.',
    description:
      'Aros de plata envejecida, livianos. Completan un look de lino oscuro sin parecer joyería de fiesta.',
    tags: ['aros', 'plata', 'liviano'],
    vector: vec({
      beach: 0.5,
      night: 0.7,
      accessory: 1,
      luxury: 0.55,
      romantic: 0.5,
      metallic: 0.8,
      summer: 0.4,
    }),
  },
  {
    id: 'mare-11',
    name: 'Bikini Coral Solar',
    brand: 'Sol Crudo',
    price: 78,
    kind: 'garment',
    fabric: 'Lycra recicada',
    colors: ['Coral'],
    sizes: ['XS', 'S', 'M', 'L'],
    image: img('photo-1611606063065-ee7946f0787a'),
    blurb: 'Color de mediodía. Para el agua, no para la cena.',
    description:
      'Bikini de corte alto en coral intenso. Pensado para nadar y secarse al sol. El neón pierde sentido cuando se apaga la luz.',
    tags: ['bikini', 'coral', 'sol', 'nadar'],
    vector: vec({
      beach: 0.95,
      night: 0.05,
      day: 0.98,
      summer: 0.95,
      casual: 0.7,
      outdoor: 0.9,
      pale: 0.2,
      swim: 1,
      light: 0.4,
      comfort: 0.6,
    }),
  },
  {
    id: 'mare-12',
    name: 'Sombrero de Palma',
    brand: 'Sol Crudo',
    price: 48,
    kind: 'accessory',
    fabric: 'Palma natural',
    colors: ['Natural'],
    sizes: ['Único'],
    image: img('photo-1521369909029-2afed882baee'),
    blurb: 'Sombra para el mediodía. De noche sobra.',
    description:
      'Ala ancha de palma trenzada. Protege del sol vertical. No cabe en una mesa de terraza nocturna.',
    tags: ['sombrero', 'palma', 'sol'],
    vector: vec({
      beach: 0.85,
      day: 0.95,
      night: 0.02,
      summer: 0.9,
      outdoor: 0.85,
      accessory: 1,
      pale: 0.7,
      nature: 0.8,
    }),
  },
  {
    id: 'mare-13',
    name: 'Chanclas de Espuma Salina',
    brand: 'Sol Crudo',
    price: 32,
    kind: 'footwear',
    fabric: 'Espuma EVA',
    colors: ['Blanco'],
    sizes: ['36-41'],
    image: img('photo-1603484477859-ae389c75d904'),
    blurb: 'Del toallón a la orilla. No salen a cenar.',
    description:
      'Chancla de espuma, agarre de agua. Útil de día; visualmente incorrecta cuando hay mantel.',
    tags: ['chancla', 'espuma', 'agua'],
    vector: vec({
      beach: 0.9,
      day: 0.9,
      night: 0.04,
      summer: 0.85,
      casual: 0.95,
      outdoor: 0.8,
      footwear: 1,
      swim: 0.5,
      comfort: 0.8,
      pale: 0.7,
    }),
  },
  {
    id: 'mare-14',
    name: 'Gafas Espejo Mediodía',
    brand: 'Sol Crudo',
    price: 96,
    kind: 'accessory',
    fabric: 'Acetato',
    colors: ['Oro espejo'],
    sizes: ['Único'],
    image: img('photo-1572635196237-14b3f281503f'),
    blurb: 'Protección solar agresiva. De noche, un estorbo.',
    description:
      'Espejo total para sol de las dos. No es accesorio de copa ni de anochecer.',
    tags: ['gafas', 'espejo', 'sol'],
    vector: vec({
      beach: 0.7,
      day: 0.95,
      night: 0.02,
      summer: 0.8,
      accessory: 1,
      outdoor: 0.75,
      metallic: 0.6,
    }),
  },
  {
    id: 'mare-15',
    name: 'Blazer Estructura Arena',
    brand: 'Oficio',
    price: 210,
    kind: 'garment',
    fabric: 'Lana fría',
    colors: ['Arena'],
    sizes: ['46', '48', '50', '52'],
    image: img('photo-1507679799987-c73779587ccf'),
    blurb: 'Hombro limpio para reuniones, no para arena.',
    description:
      'Blazer sastrero de lana fría. Estructura de oficina y ciudad. El sastre no perdona salitre.',
    tags: ['blazer', 'sastre', 'oficina'],
    vector: vec({
      office: 0.96,
      formal: 0.9,
      urban: 0.8,
      indoor: 0.7,
      day: 0.7,
      mens: 0.7,
      layering: 0.6,
      luxury: 0.65,
      travel: 0.3,
    }),
  },
  {
    id: 'mare-16',
    name: 'Pantalón Sastre de Verano',
    brand: 'Oficio',
    price: 148,
    kind: 'garment',
    fabric: 'Lana tropic',
    colors: ['Topo'],
    sizes: ['46', '48', '50', '52'],
    image: img('photo-1617137968427-85924c800a22'),
    blurb: 'Respirable en sala con aire acondicionado.',
    description:
      'Sastre de lana tropic, pinza suave. Pensado para despacho en julio, no para deck mojado.',
    tags: ['sastre', 'oficina', 'verano'],
    vector: vec({
      office: 0.92,
      formal: 0.85,
      summer: 0.55,
      indoor: 0.75,
      urban: 0.7,
      light: 0.45,
      mens: 0.75,
      comfort: 0.5,
    }),
  },
  {
    id: 'mare-17',
    name: 'Camisa Popelín Helada',
    brand: 'Oficio',
    price: 88,
    kind: 'garment',
    fabric: 'Popelín de algodón',
    colors: ['Blanco'],
    sizes: ['S', 'M', 'L', 'XL'],
    image: img('photo-1596755094514-f87e34085b2c'),
    blurb: 'El blanco de reunión. Impecable bajo fluorescentes.',
    description:
      'Popelín denso, cuello rígido, puño de botón. Lenguaje de oficina, no de orilla.',
    tags: ['camisa', 'popelin', 'oficina'],
    vector: vec({
      office: 0.9,
      formal: 0.8,
      day: 0.7,
      indoor: 0.8,
      pale: 0.85,
      mens: 0.6,
      urban: 0.6,
      summer: 0.35,
    }),
  },
  {
    id: 'mare-18',
    name: 'Mocasín de Cuero Tostado',
    brand: 'Oficio',
    price: 176,
    kind: 'footwear',
    fabric: 'Cuero vacuno',
    colors: ['Tostado'],
    sizes: ['40', '41', '42', '43', '44'],
    image: img('photo-1533867617858-e7b97e060509'),
    blurb: 'Suela de cuero para mármol, no para salitre.',
    description:
      'Mocasín clásico, palma de cuero. Desliza en lobby. La arena lo destroza.',
    tags: ['mocasin', 'cuero', 'oficina'],
    vector: vec({
      office: 0.85,
      formal: 0.7,
      urban: 0.75,
      indoor: 0.65,
      footwear: 1,
      mens: 0.7,
      luxury: 0.55,
      day: 0.6,
    }),
  },
  {
    id: 'mare-19',
    name: 'Zapatilla Tempo Agua',
    brand: 'Ritmo',
    price: 134,
    kind: 'footwear',
    fabric: 'Mesh hidrófugo',
    colors: ['Grafito'],
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    image: img('photo-1542291026-7eec264c27ff'),
    blurb: 'Agarre cuando el asfalto reluce mojado.',
    description:
      'Running con mesh de secado rápido y suela que no patina en lluvia. Hecha para entrenar, no para copas.',
    tags: ['running', 'lluvia', 'agarre', 'deporte'],
    vector: vec({
      sport: 1,
      rain: 0.95,
      outdoor: 0.9,
      urban: 0.55,
      footwear: 1,
      comfort: 0.8,
      day: 0.6,
      light: 0.5,
    }),
  },
  {
    id: 'mare-20',
    name: 'Short Técnico 13 cm',
    brand: 'Ritmo',
    price: 58,
    kind: 'garment',
    fabric: 'Nylon elástico',
    colors: ['Negro'],
    sizes: ['S', 'M', 'L', 'XL'],
    image: img('photo-1571019614242-c5c5dee9f50b'),
    blurb: 'Bolsillo interior para la llave. Cero arrastre.',
    description:
      'Short de entrenamiento, entrepierna 13 cm, no se empapa. Solo existe en la lógica del kilometraje.',
    tags: ['short', 'running', 'tecnico'],
    vector: vec({
      sport: 0.96,
      rain: 0.4,
      outdoor: 0.8,
      light: 0.7,
      comfort: 0.75,
      day: 0.7,
    }),
  },
  {
    id: 'mare-21',
    name: 'Chaqueta Windshell',
    brand: 'Ritmo',
    price: 122,
    kind: 'garment',
    fabric: 'Nylon 20D',
    colors: ['Niebla'],
    sizes: ['S', 'M', 'L', 'XL'],
    image: img('photo-1591047139829-d91aecb6caea'),
    blurb: 'Corta el viento y la llovizna sin peso.',
    description:
      'Cazadora ultraligera empaquetable. Cierra el agua fina. Se guarda en su bolsillo al terminar el fondo.',
    tags: ['chaqueta', 'lluvia', 'viento', 'running'],
    vector: vec({
      sport: 0.85,
      rain: 0.92,
      outdoor: 0.9,
      layering: 0.8,
      light: 0.9,
      urban: 0.4,
      travel: 0.55,
    }),
  },
  {
    id: 'mare-22',
    name: 'Vestido Lentejuela Órbita',
    brand: 'Hora Cero',
    price: 240,
    kind: 'look',
    fabric: 'Tul bordado',
    colors: ['Negro cristal'],
    sizes: ['XS', 'S', 'M'],
    image: img('photo-1566174053879-31528523f8ae'),
    blurb: 'Hecho para track lighting, no para humedad marina.',
    description:
      'Mini de lentejuela densa. Pesa, brilla y pide pista. El salitre y la arena no son su clima.',
    tags: ['lentejuela', 'fiesta', 'mini'],
    vector: vec({
      party: 0.98,
      night: 0.9,
      formal: 0.5,
      indoor: 0.8,
      dark: 0.7,
      dress: 1,
      luxury: 0.8,
      metallic: 0.85,
      romantic: 0.4,
      beach: 0.05,
    }),
  },
  {
    id: 'mare-23',
    name: 'Stiletto Charol',
    brand: 'Hora Cero',
    price: 188,
    kind: 'footwear',
    fabric: 'Charol',
    colors: ['Negro'],
    sizes: ['36', '37', '38', '39'],
    image: img('photo-1543163521-1bf539c55dd2'),
    blurb: 'Diez centímetros de intención. Madera de deck no incluida.',
    description:
      'Tacón aguja de charol. Dominante en mármol. Peligroso en tablones y arena.',
    tags: ['tacon', 'charol', 'fiesta'],
    vector: vec({
      party: 0.9,
      night: 0.85,
      formal: 0.75,
      indoor: 0.8,
      footwear: 1,
      luxury: 0.7,
      metallic: 0.3,
      romantic: 0.55,
      beach: 0.02,
    }),
  },
  {
    id: 'mare-24',
    name: 'Abrigo Lana Camel',
    brand: 'Latitud Norte',
    price: 320,
    kind: 'garment',
    fabric: 'Lana doble faz',
    colors: ['Camel'],
    sizes: ['S', 'M', 'L'],
    image: img('photo-1539533018447-63fcce2678e3'),
    blurb: 'Abrigo de invierno urbano. Demasiado para un clima salado y cálido.',
    description:
      'Doble faz camel, peso de diciembre. Ciudad fría, andén, cristalera. No hay diálogo con el trópico.',
    tags: ['abrigo', 'lana', 'invierno'],
    vector: vec({
      winter: 0.98,
      warm: 0.95,
      urban: 0.8,
      formal: 0.55,
      layering: 0.7,
      luxury: 0.75,
      outdoor: 0.6,
      knit: 0.3,
    }),
  },
  {
    id: 'mare-25',
    name: 'Jersey Cashmere Niebla',
    brand: 'Latitud Norte',
    price: 210,
    kind: 'garment',
    fabric: 'Cashmere 12 gauge',
    colors: ['Niebla'],
    sizes: ['S', 'M', 'L', 'XL'],
    image: img('photo-1434389677669-e08b4cac3105'),
    blurb: 'Calor seco de interior. El viento húmedo no le sienta.',
    description:
      'Jersey de cashmere, cuello caja. Oficinas frías y fines de semana de interior. La humedad marina lo mata.',
    tags: ['jersey', 'cashmere', 'invierno'],
    vector: vec({
      winter: 0.9,
      warm: 0.88,
      indoor: 0.7,
      knit: 1,
      comfort: 0.85,
      luxury: 0.8,
      casual: 0.5,
    }),
  },
  {
    id: 'mare-26',
    name: 'Vestido Satén Cereza',
    brand: 'Hora Cero',
    price: 196,
    kind: 'look',
    fabric: 'Satén de seda',
    colors: ['Cereza'],
    sizes: ['XS', 'S', 'M', 'L'],
    image: img('photo-1595777457583-95e059d581b8'),
    blurb: 'Silueta de cita. Luz baja, mesa pequeña, copa larga.',
    description:
      'Slip dress de satén cereza. Sesgo que sigue el cuerpo. Para una cena íntima, no para caminar orilla.',
    tags: ['saten', 'cita', 'sesgo', 'rojo'],
    vector: vec({
      romantic: 0.98,
      night: 0.88,
      party: 0.45,
      formal: 0.5,
      indoor: 0.7,
      dress: 1,
      luxury: 0.78,
      dark: 0.4,
      beach: 0.12,
    }),
  },
  {
    id: 'mare-27',
    name: 'Blusa de Seda Cruda',
    brand: 'Costa Quiet',
    price: 118,
    kind: 'garment',
    fabric: 'Seda cruda',
    colors: ['Marfil'],
    sizes: ['XS', 'S', 'M', 'L'],
    image: img('photo-1483985988355-763728e1935b'),
    blurb: 'Caída viva, casi ruido de tela. Sirve a una mesa y a un tren.',
    description:
      'Blusa de seda cruda, botón escondido. Vista de cita o de palco. El marfil pide interior.',
    tags: ['blusa', 'seda', 'marfil'],
    vector: vec({
      romantic: 0.7,
      formal: 0.55,
      indoor: 0.6,
      pale: 0.8,
      luxury: 0.65,
      office: 0.3,
      night: 0.45,
    }),
  },
  {
    id: 'mare-28',
    name: 'Mono Utilitario',
    brand: 'Deriva',
    price: 164,
    kind: 'look',
    fabric: 'Algodón técnico',
    colors: ['Oliva'],
    sizes: ['S', 'M', 'L'],
    image: img('photo-1485968579580-b6d095142e6e'),
    blurb: 'Un solo gesto para un embarque. Bolsillos que sí sirven.',
    description:
      'Mono con cincha y bolsillos cargo limpios. Viaja, se sienta doce horas, no se arruga como un vestido.',
    tags: ['mono', 'viaje', 'utilitario'],
    vector: vec({
      travel: 0.96,
      casual: 0.8,
      outdoor: 0.6,
      comfort: 0.85,
      urban: 0.5,
      layering: 0.2,
      day: 0.7,
    }),
  },
  {
    id: 'mare-29',
    name: 'Mochila de Cabina',
    brand: 'Deriva',
    price: 132,
    kind: 'accessory',
    fabric: 'Nylon ballístico',
    colors: ['Negro'],
    sizes: ['Único'],
    image: img('photo-1553062407-98eeb64c6a62'),
    blurb: 'Cabe bajo el asiento. Portátil, cable, una prenda de más.',
    description:
      'Mochila de cabina, 20 litros, cremalleras silenciosas. Lógica de aeropuerto, no de copa.',
    tags: ['mochila', 'viaje', 'cabina'],
    vector: vec({
      travel: 1,
      urban: 0.7,
      accessory: 1,
      outdoor: 0.4,
      comfort: 0.6,
      dark: 0.7,
    }),
  },
  {
    id: 'mare-30',
    name: 'Jeans Relajados Crudo',
    brand: 'Sal',
    price: 118,
    kind: 'garment',
    fabric: 'Denim 12 oz',
    colors: ['Crudo'],
    sizes: ['36', '38', '40', '42'],
    image: img('photo-1541099649105-f69ad21f3246'),
    blurb: 'Caída relajada de ciudad. El salitre los deja rígidos.',
    description:
      'Denim crudo, tiro medio, pierna ancha. Uniforme urbano. No es tejido de orilla.',
    tags: ['jeans', 'denim', 'ciudad'],
    vector: vec({
      casual: 0.92,
      urban: 0.9,
      day: 0.7,
      comfort: 0.7,
      mens: 0.4,
    }),
  },
  {
    id: 'mare-31',
    name: 'Hoodie Minimal',
    brand: 'Sal',
    price: 92,
    kind: 'garment',
    fabric: 'Felpa orgánica',
    colors: ['Gris piedra'],
    sizes: ['S', 'M', 'L', 'XL'],
    image: img('photo-1556821840-3a63f95609a7'),
    blurb: 'Capa de descanso. El lujo aquí es no pensar.',
    description:
      'Hoodie sin logo, felpa pesada. Sofá, aeropuerto, madrugón. Demasiado doméstico para una terraza frente al mar de noche.',
    tags: ['hoodie', 'felpa', 'casual'],
    vector: vec({
      casual: 0.95,
      comfort: 0.95,
      urban: 0.6,
      knit: 0.55,
      indoor: 0.6,
      travel: 0.4,
    }),
  },
  {
    id: 'mare-32',
    name: 'Sneaker Canvas',
    brand: 'Sal',
    price: 78,
    kind: 'footwear',
    fabric: 'Lona',
    colors: ['Crudo'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    image: img('photo-1549298916-b41d501d3772'),
    blurb: 'Lona de acera. El agua salada la mancha para siempre.',
    description:
      'Sneaker de lona cruda, suela vulcanizada. Ciudad seca. La orilla no le perdona.',
    tags: ['sneaker', 'lona', 'ciudad'],
    vector: vec({
      casual: 0.9,
      urban: 0.85,
      footwear: 1,
      day: 0.7,
      comfort: 0.7,
      pale: 0.6,
    }),
  },
  {
    id: 'mare-33',
    name: 'Guayabera de Lino',
    brand: 'MARE Atelier',
    price: 136,
    kind: 'garment',
    fabric: 'Lino cubano',
    colors: ['Marfil profundo'],
    sizes: ['S', 'M', 'L', 'XL'],
    image: img('photo-1552374196-1ab2a1c593e8'),
    blurb: 'Alforzas limpias, fresco, correcto cuando el calor no afloja.',
    description:
      'Guayabera de lino, cuatro bolsillos ciegos. El marfil profundo aguanta una terraza al anochecer sin parecer t-shirt.',
    tags: ['guayabera', 'lino', 'alforza'],
    vector: vec({
      beach: 0.7,
      night: 0.62,
      summer: 0.88,
      casual: 0.55,
      formal: 0.35,
      outdoor: 0.7,
      light: 0.9,
      mens: 0.9,
      linen: 1,
      comfort: 0.8,
      travel: 0.5,
    }),
  },
  {
    id: 'mare-34',
    name: 'Bermuda Tailored',
    brand: 'MARE Atelier',
    price: 108,
    kind: 'garment',
    fabric: 'Algodón sastre',
    colors: ['Tinta'],
    sizes: ['46', '48', '50', '52'],
    image: img('photo-1617127365659-c47fa864d8bc'),
    blurb: 'Largo correcto, pinza, se puede sentar a una mesa.',
    description:
      'Bermuda sastrera tinta. Rodilla tapada, no sport. Diálogo posible con sandalia metalizada y camisa de lino.',
    tags: ['bermuda', 'sastre', 'verano'],
    vector: vec({
      beach: 0.58,
      night: 0.55,
      summer: 0.85,
      casual: 0.5,
      outdoor: 0.6,
      light: 0.7,
      dark: 0.7,
      mens: 0.85,
      comfort: 0.7,
      linen: 0.25,
    }),
  },
  {
    id: 'mare-35',
    name: 'Alpargata de Yute',
    brand: 'Litoral',
    price: 72,
    kind: 'footwear',
    fabric: 'Lona y yute',
    colors: ['Negro'],
    sizes: ['40', '41', '42', '43', '44'],
    image: img('photo-1603808033192-082d6919d3e1'),
    blurb: 'Suela de yute, capellada negra. Orilla y mesa sin cambiar de zapato.',
    description:
      'Alpargata negra de yute compacto. Informal con oficio. Transita arena compacta y terraza.',
    tags: ['alpargata', 'yute', 'negro'],
    vector: vec({
      beach: 0.8,
      night: 0.6,
      summer: 0.85,
      casual: 0.7,
      outdoor: 0.75,
      dark: 0.7,
      footwear: 1,
      comfort: 0.75,
      mens: 0.55,
      nature: 0.5,
    }),
  },
  {
    id: 'mare-36',
    name: 'Pañuelo de Gasa Salitre',
    brand: 'Litoral',
    price: 46,
    kind: 'accessory',
    fabric: 'Gasa de seda',
    colors: ['Humo'],
    sizes: ['Único'],
    image: img('photo-1601924994987-69e26d2b0a45'),
    blurb: 'Se anuda al cuello o al bolso cuando baja la temperatura un grado.',
    description:
      'Pañuelo de gasa, 70 cm. Peso cero, gesto de noche. No abriga: completa.',
    tags: ['panuelo', 'gasa', 'cuello'],
    vector: vec({
      beach: 0.55,
      night: 0.75,
      summer: 0.45,
      accessory: 1,
      layering: 0.55,
      luxury: 0.5,
      romantic: 0.55,
      light: 0.8,
      dark: 0.4,
    }),
  },
];

module.exports = { products };
